---
title: "Time series data visualization"
author: "Halef Caetano"
date: "1/17/2024"
output: html_document
---

```{r, include=FALSE, message = FALSE, warning=FALSE}
library(tidyverse)
library(zoo)
crime_data <- readRDS("Crime3years.rds")
crime_data_selected <- crime_data %>%
  filter(Date >= as.Date("2018-01-01 00:00:00") & Date <= as.Date("2019-12-31 00:00:00"))
crime_data_selected <- crime_data_selected %>%
  mutate(hour = hour(Date),
         week = weekdays(Date),
         month = month(Date),
         year = year(Date),
         weeknum = strftime(Date, format = '%V'), 
         dates = as.Date(strftime(Date, format = '%F')))  
```


# Create plots at different scales

## * Plot at a hourly scale


```{r, echo=FALSE, message = FALSE, warning=FALSE}
ggplot(crime_data_selected, aes(x = Date, y = Battery, color = "red")) +
  geom_line() +
  geom_point() +  
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago",
       x = "Hourly",
       y = "Number of Crimes") +
  scale_x_datetime(date_labels = "%m/%d/%y-%H:%M:%S")
```


## * Plot at a weekly scale

```{r, echo=FALSE, message = FALSE, warning=FALSE}
crime_data_weekly <- crime_data_selected %>%
  group_by(weeknum, year) %>%
  summarize(yearmonth = min(dates), 
            case_weekly = sum(Battery)) %>%
  filter(year != 2020) 

ggplot(crime_data_weekly, aes(x = yearmonth, y = case_weekly, color = factor(year))) +
  geom_line() +
  geom_point() +
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago",
       x = "Year-Week",
       y = "Number of Crimes") +
  scale_x_date(date_labels = "%Y/%U")
```


```{r, echo=FALSE, message = FALSE, warning=FALSE}
crime_data_monthly <- crime_data_selected %>%
  group_by(month, year) %>%
  summarize(yearmonth = as.Date(as.yearmon(paste0(year, month), "%Y%m")),
            total_crimes = sum(Battery))

ggplot(crime_data_monthly, aes(x = yearmonth, y = total_crimes, color = factor(year))) +
  geom_line() + geom_point() +
  labs(title = "Battery Crime from 2018-01-01 to 2019-12-31 in Chicago",
       x = "Year-Month",
       y = "Number of Crimes") +
  scale_x_date(date_labels = "%Y-%b")
```


```{r, echo=FALSE, message = FALSE, warning=FALSE}
crime_data_monthly_stacked <- crime_data_selected %>%
  group_by(month, year) %>%
  summarize(yearmonth = as.Date(as.yearmon(paste0(year, month), "%Y%m")),
            total_crimes = sum(Battery)) %>%
  ungroup()

ggplot(crime_data_monthly_stacked, aes(x = month, y = total_crimes, group = year, color = factor(year))) +
  geom_line() + geom_point() +
  labs(title = "Battery Crime in Chicago",
       x = "Month",
       y = "Number of Crimes",
       color = "Year") +
  scale_x_continuous(breaks = 1:12, labels = month.abb)
```

